import {
  AlertOctagon,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Ban,
  Bell,
  Bike,
  Briefcase,
  Calendar,
  Camera,
  CarTaxiFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  Clock,
  CreditCard,
  Crown,
  Delete,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Flag,
  Gift,
  Hand,
  Headset,
  Home,
  Image as ImageIcon,
  IndianRupee,
  Info,
  Landmark,
  LifeBuoy,
  ListChecks,
  Loader,
  Locate,
  Lock,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  Navigation,
  Package,
  PackageX,
  Pencil,
  Phone,
  Plus,
  QrCode,
  RefreshCw,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Siren,
  Sparkles,
  Star,
  Store,
  Timer,
  Trash2,
  TrendingUp,
  Truck,
  Upload,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  WifiOff,
  X,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react-native';

import { colors, type ColorToken } from '@/theme';

/** Lucide icons used by the Figma file, addressed by their Figma layer names. */
export const ICONS = {
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  ban: Ban,
  bell: Bell,
  bike: Bike,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  'car-taxi-front': CarTaxiFront,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-check': CircleCheck,
  'help-circle': CircleHelp,
  'circle-help': CircleHelp,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  'credit-card': CreditCard,
  crown: Crown,
  delete: Delete,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  flag: Flag,
  gift: Gift,
  hand: Hand,
  headset: Headset,
  home: Home,
  image: ImageIcon,
  'indian-rupee': IndianRupee,
  info: Info,
  landmark: Landmark,
  'life-buoy': LifeBuoy,
  'list-checks': ListChecks,
  loader: Loader,
  locate: Locate,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  map: MapIcon,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'more-horizontal': MoreHorizontal,
  navigation: Navigation,
  package: Package,
  'package-x': PackageX,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  'qr-code': QrCode,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'scan-line': ScanLine,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  siren: Siren,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  timer: Timer,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  truck: Truck,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface IconProps extends Omit<LucideProps, 'color' | 'size'> {
  name: IconName;
  size?: number;
  color?: ColorToken | (string & {});
  strokeWidth?: number;
}

export const Icon = ({ name, size = 20, color = 'ink', strokeWidth = 2, ...rest }: IconProps) => {
  const Cmp = ICONS[name];
  const resolved = color in colors ? colors[color as ColorToken] : color;
  return <Cmp size={size} color={resolved} strokeWidth={strokeWidth} {...rest} />;
};
