import { useMemo, useState } from 'react';
import { Image, Linking, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';

import { AppText, Card, ErrorState, LoadingState, Screen, SecondaryButton, toast } from '@/components/ui';
import { AppHeader } from '@/components/app';
import { WeeklyChart } from '@/features/earnings/components/WeeklyChart';
import { isoWeekOf, seriesDate, weekRangeLabel } from '@/features/earnings/week';
import { useEarnings } from '@/hooks';
import { getDataProvider } from '@/providers';
import { isLocalDemo } from '@/config/env';
import { colors, fontFamily, spacing } from '@/theme';
import { formatINR } from '@/utils/format';

/** Figma earnings-weekly: weekly total, daily histogram, efficiency insights, DOWNLOAD DETAILED PDF. */
export default function WeeklyStatementScreen() {
  const { data, isLoading, error, refetch } = useEarnings('week');
  const [downloading, setDownloading] = useState(false);

  const week = useMemo(() => {
    const last = data?.series[data.series.length - 1];
    return isoWeekOf(last ? seriesDate(last) : new Date());
  }, [data]);

  const download = async () => {
    setDownloading(true);
    try {
      const url = await getDataProvider().getStatementUrl(week);
      if (isLocalDemo) {
        toast.show(`Statement PDF is generated by the server; demo link: ${url}`);
        return;
      }
      const can = await Linking.canOpenURL(url);
      if (!can) {
        toast.error('No app can open the statement link on this device.');
        return;
      }
      await Linking.openURL(url);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Could not fetch the weekly statement.');
    } finally {
      setDownloading(false);
    }
  };

  const insights = data?.insights ?? [];

  return (
    <Screen scroll footer={<SecondaryButton label="DOWNLOAD DETAILED PDF" onPress={() => void download()} loading={downloading} disabled={!data} />}>
      <AppHeader title="Weekly Statement" backIcon="chevron-left" onHelp={() => router.push('/support' as never)} />

      {isLoading && !data ? (
        <LoadingState label="Loading weekly statement…" />
      ) : error && !data ? (
        <ErrorState title="Couldn't load the weekly statement" body={error instanceof Error ? error.message : 'Check your connection and try again.'} onRetry={() => void refetch()} />
      ) : data ? (
        <View style={styles.body}>
          <Card radius={32} padding={spacing.x3l} borderWidth={1} borderColor={colors.borderSubtle} gap={spacing.xs}>
            <AppText color="textSecondary" style={styles.heroLabel}>
              TOTAL EARNINGS ({weekRangeLabel(data.series) || data.periodLabel.toUpperCase()})
            </AppText>
            <AppText variant="display" style={styles.heroAmount} accessibilityLabel={`Total earnings ${formatINR(data.total, { decimals: 2 })}`}>
              {formatINR(data.total, { decimals: 2 })}
            </AppText>
            <AppText style={styles.heroSub}>
              {data.deliveries} {data.deliveries === 1 ? 'Delivery' : 'Deliveries'} Completed Successfully
            </AppText>
          </Card>

          <Card radius={32} padding={18} borderWidth={2} borderColor={colors.border} gap={spacing.xxl}>
            <AppText variant="title">DAILY HISTOGRAM</AppText>
            <WeeklyChart series={data.series} />
          </Card>

          <Card radius={32} padding={spacing.xxl} borderWidth={1} borderColor={colors.borderSubtle} gap={spacing.base}>
            <AppText variant="chip">Efficiency Insights</AppText>
            {insights.length === 0 ? (
              <AppText color="textSecondary" style={styles.insightBody}>
                Insights appear once you complete deliveries this week.
              </AppText>
            ) : (
              insights.map((ins, i) => (
                <View key={`${ins.title}-${i}`} style={styles.insightRow}>
                  <Image source={require('@/assets/figma/icon-star.png')} style={styles.star} resizeMode="contain" accessibilityIgnoresInvertColors />
                  <View style={styles.insightTexts}>
                    <AppText variant="label" color={ins.tone === 'warning' ? 'danger' : 'ink'}>
                      {ins.title}
                    </AppText>
                    <AppText color="textSecondary" style={styles.insightBody}>
                      {ins.body}
                    </AppText>
                  </View>
                </View>
              ))
            )}
          </Card>

          <AppText variant="bodySm" color="textMuted" align="center">
            Statement {week} · Earnings rule v{data.ruleVersion}
          </AppText>
        </View>
      ) : null}
    </Screen>
  );
}

const styles = StyleSheet.create({
  body: { gap: spacing.x3l, paddingTop: spacing.lg },
  heroLabel: { fontFamily: fontFamily.manropeBold, fontSize: 13, lineHeight: 18 },
  heroAmount: { fontFamily: fontFamily.manropeExtraBold, fontSize: 32, lineHeight: 40 },
  heroSub: { fontFamily: fontFamily.manropeSemiBold, fontSize: 12, lineHeight: 16 },
  insightRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  insightTexts: { flex: 1, gap: spacing.xxs },
  star: { width: 16, height: 16, marginTop: 1 },
  insightBody: { fontFamily: fontFamily.manropeSemiBold, fontSize: 12, lineHeight: 17 },
});
