/** Fixed component dimensions from the Figma spec. */
export const dimensions = {
  figmaWidth: 390,
  figmaHeight: 844,
  primaryButtonHeight: 56,
  inputHeight: 56,
  smallButtonHeight: 44,
  chipHeight: 36,
  iconSm: 16,
  iconMd: 20,
  iconLg: 24,
  iconXl: 32,
  tabWidth: 80,
  tabIconBox: 32,
  homeIndicatorWidth: 134,
  homeIndicatorHeight: 5,
  minTouchTarget: 44,
  radarOuter: 100,
  radarInner: 64,
  avatarSm: 40,
  avatarMd: 56,
  avatarLg: 96,
  otpBox: 56,
  mapHeightCompact: 220,
  mapHeightTall: 320,
} as const;
